### ISSUE TITLE
what if I want to keep iframes?

### ISSUE THREAD

**Issue by zachwhalen** [itsKaspar/tomato#9]
Hello,

Sometimes for a particular effect, it's desirable to keep iframes instead of always discarding them. How would I accomplish that option in the script? I've started poking at it, but I don't know enough about the AVI file structure to tell where that discarding happens. I suspect it happens when the frame indices are detected and rebuilt, but I'm no sure what else should go [in that place](https://github.com/itsKaspar/tomato/blob/10585d8bff7d21bc34b1e3921b09379bb9b16e7f/tomato.py#L127) in order to preserve the iframe.

Any thoughts?

**Comment by genmeblog** [comment]
Try to set `-k 1.0`.

As far as I remember (and read the code) iframes are removed using frame size condition (https://github.com/itsKaspar/tomato/blob/master/tomato.py#L157).

**Comment by zachwhalen** [comment]
Yeah, I think you're right -- that works. Thanks!
